### ISSUE TITLE
Default Go version already on go.mod

### ISSUE THREAD

**Issue by flibustenet** [Scalingo/go-buildpack#16]
Hi,
In `go.mod` the minimum Go version is already specified at the end of the file.
I was surprise that go-buildpack didn't recognize this and that i needed to add the comment `// +scalingo goVersion`.
Maybe there is a reason other than legacy ?
edit: i see the same issue on heroku https://github.com/heroku/heroku-buildpack-go/issues/378

**Comment by EtienneM** [comment]
Hi,

Thanks for your message. We were waiting for more information from the upstream maintainer on the PR https://github.com/heroku/heroku-buildpack-go/pull/411. As it seems kind of stuck on this side, we will investigate this change on our side.

**Comment by abitrolly** [comment]
If you can sponsor this work, I can see if I can fix the remaining tests in #411. I did what I can, but as am not employed by Heroku, spending more time learning its codebase is not sustainable.

**Comment by abitrolly** [comment]
Just a notice that upstream issue is fixed.

**Comment by EtienneM** [comment]
Thanks for the notification. We also noticed it but it's unfortunately not yet release :(

**Comment by EtienneM** [comment]
@flibustenet the fix for this issue just got released. It is currently being deployed on our servers and should be available in the coming hour.
