### ISSUE TITLE
Reference to mattes/migrate in bin/compile should use the new repo

### ISSUE THREAD

**Issue by EtienneM** [Scalingo/go-buildpack#3]
github.com/mattes/migrate migrated to https://github.com/golang-migrate/migrate

References are here: https://github.com/Scalingo/go-buildpack/blob/master/bin/compile#L162-L172

**Comment by Soulou** [comment]
Why is it a bug, is something broken somewhere?

Upstream buildpack from heroku is still on `mattes/migrate`
